# Generated by Django 4.2.2 on 2023-06-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='puplish_date',
            field=models.DateTimeField(),
        ),
    ]
